<a href="https://colab.research.google.com/github/manower35/Hussain786/blob/main/PyTorch_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("PyTorch is a deep learning library")

PyTorch is a deep learning library


In [ ]:
!nvidia-smi

Wed Jul 16 08:02:02 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   53C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
!nvidia-smi

Wed Jul 16 08:04:41 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   46C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Creating Tensor

In [ ]:
scalar = torch.tensor(10)
scalar

tensor(10)

In [ ]:
scalar = torch.tensor(0)

In [ ]:
scalar.ndim

0

In [8]:
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [10]:
vector = torch.tensor([0,1])
vector

tensor([0, 1])

In [11]:
vector.ndim

1

In [15]:
import torch
metrix = torch.tensor([[1,2], [4,6]])
metrix

tensor([[1, 2],
        [4, 6]])

In [17]:
metrix.ndim

2

In [18]:
metrix.shape

torch.Size([2, 2])

In [19]:
metrix[1]

tensor([4, 6])

TENSOR

In [20]:
TENSOR = torch.tensor([[[2,6,9],[3,7,5],[0,4,1]]])
TENSOR

tensor([[[2, 6, 9],
         [3, 7, 5],
         [0, 4, 1]]])

In [23]:
TENSOR.shape

torch.Size([1, 3, 3])

In [25]:
TENSOR.size()

torch.Size([1, 3, 3])

In [27]:
TENSOR[0]

tensor([[2, 6, 9],
        [3, 7, 5],
        [0, 4, 1]])

In [28]:
TENSOR[0][1]

tensor([3, 7, 5])

In [29]:
TENSOR[0][1][2]

tensor(5)

Random Tensor

In [31]:
random_num = torch.rand(3,4)
random_num

tensor([[0.2503, 0.4024, 0.1361, 0.8538],
        [0.7436, 0.4117, 0.5461, 0.4638],
        [0.2719, 0.0724, 0.2047, 0.3192]])

In [32]:
random_num = torch.rand(1,5)
random_num

tensor([[0.4322, 0.7252, 0.8880, 0.3982, 0.5806]])